#!/usr/bin/env ruby

# quick_test.rb - Quick validation test for refactoring changes
#
# This script performs a fast validation test to ensure the event_checker.rb
# script still works after refactoring changes. It runs a minimal test case
# and validates basic functionality.
#
# Usage: ruby quick_test.rb

require 'date'
require 'fileutils'
require 'tempfile'

class QuickTester
  def initialize
    @test_dir = "quick_test_#{Time.now.strftime("%Y%m%d_%H%M%S")}"
    @start_date = Date.today
    @end_date = Date.today + 1  # 2-day range for speed
    
    puts "⚡ Quick Refactoring Validation Test"
    puts "=" * 40
    puts "📅 Testing date range: #{@start_date} to #{@end_date}"
  end
  
  def run_test
    # Create temporary test directory
    FileUtils.mkdir_p(@test_dir)
    
    begin
      # Backup existing files
      backup_files
      
      # Run the test
      success = run_event_checker
      
      if success
        # Validate outputs
        validate_outputs
      else
        puts "❌ Event checker execution failed!"
        show_error_log
        return false
      end
      
    ensure
      # Restore original files
      restore_files
      
      # Clean up test directory
      FileUtils.rm_rf(@test_dir) if Dir.exist?(@test_dir)
    end
    
    true
  end
  
  private
  
  def backup_files
    puts "💾 Backing up existing files..."
    
    files_to_backup = ['upcoming.md', 'ongoing.md', 'archive.md']
    
    files_to_backup.each do |file|
      if File.exist?(file)
        backup_path = File.join(@test_dir, "backup_#{file}")
        FileUtils.cp(file, backup_path)
      end
    end
  end
  
  def restore_files
    puts "🔄 Restoring original files..."
    
    Dir.glob(File.join(@test_dir, "backup_*")).each do |backup_file|
      original_file = File.basename(backup_file).sub('backup_', '')
      FileUtils.cp(backup_file, original_file)
    end
  end
  
  def run_event_checker
    puts "🏃 Running event_checker.rb..."
    
    # Create input file
    input_file = File.join(@test_dir, "input.txt")
    File.write(input_file, "#{@start_date.strftime('%Y-%m-%d')}\n#{@end_date.strftime('%Y-%m-%d')}\n")
    
    # Run with timeout to prevent hanging
    output_file = File.join(@test_dir, "output.txt")
    error_file = File.join(@test_dir, "error.txt")
    
    # Use gtimeout if available (brew install coreutils), otherwise use plain ruby with a reasonable expectation
    timeout_cmd = system("which gtimeout > /dev/null 2>&1") ? "gtimeout 120" : ""
    cmd = "cd #{Dir.pwd} && #{timeout_cmd} ruby event_checker.rb < #{input_file} > #{output_file} 2> #{error_file}"
    
    # Execute and capture result
    result = system(cmd)
    
    if result
      puts "   ✅ Execution completed successfully"
    else
      puts "   ❌ Execution failed or timed out"
    end
    
    result
  end
  
  def validate_outputs
    puts "🔍 Validating outputs..."
    
    validations = [
      validate_upcoming_file,
      validate_ongoing_file,
      validate_no_crashes,
      validate_basic_functionality
    ]
    
    if validations.all?
      puts "   ✅ All validations passed!"
      return true
    else
      puts "   ❌ Some validations failed!"
      return false
    end
  end
  
  def validate_upcoming_file
    unless File.exist?('upcoming.md')
      puts "   ❌ upcoming.md not created"
      return false
    end
    
    content = File.read('upcoming.md')
    
    unless content.include?('Upcoming Cultural Events')
      puts "   ❌ upcoming.md missing header"
      return false
    end
    
    unless content.include?('Generated by Kraków Event Checker')
      puts "   ❌ upcoming.md missing version info"  
      return false
    end
    
    puts "   ✅ upcoming.md looks valid"
    true
  end
  
  def validate_ongoing_file
    unless File.exist?('ongoing.md')
      puts "   ❌ ongoing.md not created"
      return false
    end
    
    content = File.read('ongoing.md')
    
    unless content.include?('Ongoing Cultural Events')
      puts "   ❌ ongoing.md missing header"
      return false
    end
    
    puts "   ✅ ongoing.md looks valid"
    true
  end
  
  def validate_no_crashes
    error_file = File.join(@test_dir, "error.txt")
    
    if File.exist?(error_file) && File.size(error_file) > 0
      error_content = File.read(error_file)
      
      # Check for Ruby errors
      if error_content.match?(/(Error|Exception|undefined method|uninitialized constant)/i)
        puts "   ❌ Ruby errors detected:"
        puts error_content.lines.first(3).map { |line| "      #{line.strip}" }
        return false
      end
    end
    
    puts "   ✅ No crashes detected"
    true
  end
  
  def validate_basic_functionality
    output_file = File.join(@test_dir, "output.txt")
    
    unless File.exist?(output_file)
      puts "   ❌ No output captured"
      return false
    end
    
    output_content = File.read(output_file)
    
    # Check for expected output patterns
    expected_patterns = [
      /Kraków Event Checker/,
      /Searching for events/,
      /Event check completed/
    ]
    
    missing_patterns = expected_patterns.reject { |pattern| output_content.match?(pattern) }
    
    if missing_patterns.any?
      puts "   ❌ Missing expected output patterns:"
      missing_patterns.each { |pattern| puts "      #{pattern.inspect}" }
      return false
    end
    
    puts "   ✅ Basic functionality working"
    true
  end
  
  def show_error_log
    error_file = File.join(@test_dir, "error.txt")
    output_file = File.join(@test_dir, "output.txt")
    
    puts "\n📋 Execution Details:"
    
    if File.exist?(output_file)
      puts "\n--- STDOUT ---"
      puts File.read(output_file).lines.last(10)
    end
    
    if File.exist?(error_file) && File.size(error_file) > 0
      puts "\n--- STDERR ---"
      puts File.read(error_file).lines.last(10)
    end
  end
end

# Main execution
if __FILE__ == $0
  begin
    tester = QuickTester.new
    success = tester.run_test
    
    if success
      puts "\n🎉 Quick test PASSED! Refactoring appears to be working correctly."
      exit 0
    else
      puts "\n💥 Quick test FAILED! Please review the refactoring changes."
      exit 1
    end
    
  rescue Interrupt
    puts "\n❌ Quick test cancelled by user"
    exit 1
  rescue => e
    puts "\n❌ Error running quick test: #{e.message}"
    puts "🐛 #{e.backtrace.join("\n   ")}" if ENV['DEBUG']
    exit 1
  end
end